#!/bin/bash

echo "Enter number of days to list files - "
read day

echo "These files are older than $day days - "
find /home/knoldus -mtime $day -ls

echo "Want to continue ? [y/n]"
read Ans

if [[ $Ans == "Y" || $Ans == "y" ]]
then
    './linux_assignment'
else
    echo "Terminated"
fi
