#!/bin/bash

#It will search for Good word in file
echo ROWS WHO HAVE GOOD IN IT -- 
grep "Good" testfile

#It will replace Good to Bad
echo REPLACED GOOD WITH BAD -- 
sed 's/Good/Bad/g' testfile

#It will print the 2nd and 3rd column of the modified file
echo EXTRACT 2ND AND 3RD COLUMN FROM REPLACED FILE --
sed 's/Good/Bad/g' testfile | awk '{print $2,$3}'


